# When adding new food also add to random spawner located in Resources\Prototypes\Entities\Markers\Spawners\Random\Food_Drinks\food_produce.yml
# For produce that can't be immediately eaten

- type: entity
  parent: BaseItem
  id: ProduceBase
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: Sprite
    state: produce
  - type: Produce
  - type: PotencyVisuals
  - type: Appearance
  - type: Extractable
    grindableSolutionName: food

- type: entity
  parent: ProduceBase
  id: ProduceBaseRuminant
  abstract: true
  components:
  # let cows eat raw produce like wheat and oats
  - type: Edible
    requiresSpecialDigestion: true
  - type: Tag
    tags:
    - Ruminant

# For produce that can be immediately eaten

- type: entity
  parent: FoodInjectableBase
  id: FoodProduceBase
  abstract: true
  components:
  - type: SolutionContainerManager
  - type: Sprite
    state: produce
  - type: Produce
  - type: PotencyVisuals
  - type: Appearance
  - type: Extractable
    grindableSolutionName: food

# Subclasses

- type: entity
  name: wheat bushel
  description: Sigh... wheat... a-grain?
  id: WheatBushel
  parent: ProduceBaseRuminant
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/wheat.rsi
  - type: Item
    heldPrefix: produce
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Flour
          Quantity: 10
  - type: Produce
    seedId: wheat
  - type: Tag
    tags:
    - Wheat
    - Ruminant

- type: entity
  name: banana
  parent: FoodProduceBase
  id: FoodBanana
  description: Rich in potassium.
  components:
  - type: FlavorProfile
    flavors:
      - banana
  - type: Edible
    trash:
    - TrashBananaPeel
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: TrashBananaPeel
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 6
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 2
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/banana.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: banana
  - type: Tag
    tags:
    - Fruit
    - Banana
  - type: FoodSequenceElement
    entries:
      Burger: Banana
      Taco: Banana

- type: entity
  parent: BaseItem
  id: TrashBananaPeel
  name: banana peel
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/banana.rsi
    state: peel
  - type: Item
    sprite: Objects/Specific/Hydroponics/banana.rsi
    heldPrefix: peel
  - type: Slippery
  - type: StepTrigger
    intersectRatio: 0.2
  - type: CollisionWake
    enabled: false
  - type: Physics
    bodyType: Dynamic
  - type: Fixtures
    fixtures:
      slips:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.2,-0.2,0.2,0.2"
        hard: false
        layer:
        - SlipLayer
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.2,-0.2,0.2,0.2"
        density: 30
        mask:
        - ItemMask
  - type: Tag
    tags:
    - Recyclable
    - Trash
    - BananaPeel
    - Ruminant
    - WhitelistChameleon
    - HamsterWearable
  - type: Extractable
    grindableSolutionName: food
  - type: SpaceGarbage
  - type: Edible
    requiresSpecialDigestion: true
  - type: Clothing
    sprite: Objects/Specific/Hydroponics/banana.rsi
    equippedPrefix: peel
    slots:
    - HEAD
    quickEquip: false

- type: entity
  name: potato
  parent: FoodProduceBase
  id: FoodPotato
  description: The space Irish starved to death after their potato crops died. Sadly they were unable to fish for space carp due to it being the queen's space. Bringing this up to any space IRA member will drive them insane with anger.
  components:
  - type: FlavorProfile
    flavors:
      - potatoes
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/potato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: potato
  - type: Tag
    tags:
    - Potato
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Burger: Potato
      Taco: Potato

- type: entity
  name: tomato
  parent: [FoodProduceBase, ItemHeftyBase]
  id: FoodTomato
  description: I say to-mah-to, you say tom-mae-to.
  components:
  - type: FlavorProfile
    flavors:
      - tomato
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 7
        - ReagentId: Vitamin
          Quantity: 3
        - ReagentId: Water
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/tomato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: tomato
  - type: Extractable
    grindableSolutionName: food
  - type: Damageable
    damageContainer: Biological
  - type: DamageOnHighSpeedImpact
    minimumSpeed: 0.1
    damage:
      types:
        Blunt: 1
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Skewer: TomatoSkewer
      Burger: Tomato
      Taco: Tomato

- type: entity
  name: onion
  parent: FoodProduceBase
  id: FoodOnion
  description: Nothing to cry over.
  components:
  - type: FlavorProfile
    flavors:
      - onion
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 18
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/onion.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: onion
  - type: SliceableFood
    count: 5
    slice: FoodOnionSlice
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: chanterelle cluster
  parent: FoodProduceBase
  id: FoodMushroom
  description: "Cantharellus Cibarius: These jolly yellow little shrooms sure look tasty!"
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/chanterelle.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: chanterelle
  - type: Tag
    tags:
    - Vegetable
    - Mushroom

# Slices

- type: entity
  parent: FoodInjectableBase
  id: ProduceSliceBase
  abstract: true
  components:
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 3
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
  - type: Sprite
    state: slice
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Slice

- type: entity
  name: onion slice
  parent: ProduceSliceBase
  id: FoodOnionSlice
  description: Nothing to cry over.
  components:
  - type: FlavorProfile
    flavors:
      - onion
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/onion.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Vitamin
          Quantity: 1
  - type: Tag
    tags:
    - Vegetable
    - Slice
  - type: FoodSequenceElement
    entries:
      Burger: OnionSliceBurger
      Taco: OnionSlice

- type: entity
  name: chili pepper
  parent: FoodProduceBase
  id: FoodChiliPepper
  description: Spicy, best not touch your eyes.
  components:
  - type: FlavorProfile
    flavors:
      - spicy
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 18
        reagents:
          - ReagentId: Nutriment
            Quantity: 4
          - ReagentId: Vitamin
            Quantity: 4
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/chili.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: chili
  - type: Tag
    tags:
    - Vegetable
  - type: FoodSequenceElement
    entries:
      Taco: ChiliPepper
      Burger: ChiliPepper
      Skewer: ChiliPepperSkewer

- type: entity
  name: rice bushel
  description: Can be ground into rice, perfect for pudding or sake.
  id: RiceBushel
  parent: ProduceBaseRuminant
  components:
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/rice.rsi
  - type: Item
    heldPrefix: produce
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Rice
          Quantity: 10
  - type: Produce
    seedId: rice
